config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create] 
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :site do
    get 'home', to: 'home#index'
    namespace :profile do 
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update]
    end
  end

  devise_for :admins, skip: 'registrations'
  devise_for :members

  root 'site/home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  # Includes

  # Associations

  # Validations
  validates_presence_of :description

  # Callbacks

  # Scopes
  scope :order_by_description, -> { order(:description) }

  # Class Methods

  # Instance Methods

  private
    #Private Methods

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  # If the admin has full access he can see all other admins
  # else only see other admins with restricted access
  def index
    # @admins = Admin.with_full_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path,
        success: t('alerts.created_alert', item: @admin.email)
        #notice: t('alerts.created_alert', item: @admin.email)
    else
      render :new
    end
  end

  def edit
    # Uses set_admin to get admin
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path,
        success: t('alerts.updated_alert', item: @admin.email)
        #notice: t('alerts.updated_alert', item: @admin.email)
    else
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email

    if @admin.destroy
      redirect_to backoffice_admins_path,
        success: t('alerts.deleted_alert', item: admin_email)
        #notice: t('alerts.deleted_alert', item: admin_email)
    else
      render :index
    end
  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      if password_blank?
        params[:admin].except!(:password, :password_confirmation)
      end

      if @admin.blank?
        # For create action
        params.require(:admin)
          .permit(:name, :email, :role, :password, :password_confirmation)
      else
        # For edit, update and destroy actions
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params.dig(:password).blank? &&
      params.dig(:password_confirmation).blank?
    end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    if @category.errors.any?
      render :new,
      #notice: I18n.t('alerts.created_error_alert', item: @category.description)
      danger: I18n.t('alerts.created_error_alert', item: @category.description)
    else
      redirect_to backoffice_categories_path, 
      #notice: I18n.t('alerts.created_alert', item: @category.description)
      success: I18n.t('alerts.created_alert', item: @category.description)
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, 
        #notice: I18n.t('alerts.updated_alert', item: @category.description)
        success: I18n.t('alerts.updated_alert', item: @category.description)
    else
      render :edit
    end
  end

  def destroy
    category_description = @category.description
    if @category.destroy
      redirect_to backoffice_categories_path, 
        # notice: I18n.t('alerts.deleted_alert', item: category_description)
        success: I18n.t('alerts.deleted_alert', item: category_description)
    else
      render :index
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin, 
                               params[:'recipient-text'],
                               params[:'subject-text'],
                               params[:'message-text']).deliver_now
      @notify_message = t('alerts.email_sent_sucessfully_alert')
      @notify_flag = "success"
    rescue
      @notify_message = t('alerts.email_error_alert')
      @notify_flag = "error"
    end
                             
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  # customized user type in pundit
  def pundit_user
    current_admin # current_user to Pundit
  end

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)
  
  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", 
  locals: {action: t('labels.editing_label', model: Category.model_name.human) } %>

app/views/backoffice/categories/index.html.erb
<h1 class="page-header"><%= @categories.model_name.human(count: 2) %></h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('labels.listing_label', model: @categories.model_name.human(count: 2)) %>
    
    <%= link_to new_backoffice_category_path do %>
      <button type="button" class="btn btn-success btn-circle pull-right"
        style="margin-top: -5px">
        <i class="fa fa-plus"></i>
      </button>
    <% end %>
    
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
      <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>#</th>
                <th><%= @categories.human_attribute_name("description") %></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %> 
                <tr>
                  <td style="width: 50px"><%= category.id %></td>
                  <td><%= category.description %></td>
                  <td style="width: 85px">
                    <%= link_to edit_backoffice_category_path(category.id) do %>
                      <button type="button" class="btn btn-warning 
                        btn-circle">
                        <i class="fa fa-edit"></i>
                      </button>
                    <% end %>
                    <%= link_to backoffice_category_path(category.id), 
                      method: :delete, 
                      data: { confirm: I18n.t('alerts.confirm_with_alert',
                      item: category.description) } do %>
                      <button type="button" class="btn btn-danger 
                        btn-circle">
                        <i class="fa fa-trash-o"></i>
                      </button>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
      <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>
<!-- /.panel -->

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", 
    locals: {action: t('labels.creating_label', model: Category.model_name.human) }%>