config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create] 
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :site do
    get 'home', to: 'home#index'
    namespace :profile do 
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update]
    end
  end

  devise_for :admins, skip: 'registrations'
  devise_for :members

  root 'site/home#index'

end

app/views/layouts/backoffice_shared/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Back Office</a>
  </div>
  <!-- /.navbar-header -->
 
  <ul class="nav navbar-top-links navbar-right">
      <%= current_admin.email %>
      
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
            <i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-tasks">
          <li>
            <%= link_to "SB-Admin Template", '/templates/sb-admin/pages/index.html'%></b>
          </li>
          <li>
            <%= link_to "Routes", '/rails/info/routes' %></b>
          </li>
        </ul>
        <!-- /.dropdown-tasks -->
      </li>

      <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li>
              <%= link_to destroy_admin_session_path, method: :delete do %>
                  <i class="fa fa-sign-out fa-fw"></i> Logout
              <% end %>
            </li>
          </ul>
          <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li>
            <%= link_to backoffice_dashboard_path do	%>
              <i class="fa fa-dashboard fa-fw"></i> Dashboard
            <% end %>
          </li>
          <li>
            <%= link_to backoffice_categories_path do	%>
              <i class="fa fa-th-list fa-fw"></i> 
              <%= Category.model_name.human(count: 2) %>
            <% end %>
          </li>
          <li>
            <%= link_to backoffice_admins_path do	%>
              <i class="fa fa-users fa-fw"></i> 
              <%= Admin.model_name.human(count: 2) %>
            <% end %>
          </li>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>