config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    resources :send_mail, only: [:edit, :create] 
    resources :categories, except: [:show]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :site do
    get 'home', to: 'home#index'
    namespace :profile do 
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update]
    end
  end

  devise_for :admins, skip: 'registrations'
  devise_for :members

  root 'site/home#index'

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  # If the admin has full access he can see all other admins
  # else only see other admins with restricted access
  def index
    # @admins = Admin.with_full_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path,
        success: t('alerts.created_alert', item: @admin.email)
        #notice: t('alerts.created_alert', item: @admin.email)
    else
      render :new
    end
  end

  def edit
    # Uses set_admin to get admin
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path,
        success: t('alerts.updated_alert', item: @admin.email)
        #notice: t('alerts.updated_alert', item: @admin.email)
    else
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email

    if @admin.destroy
      redirect_to backoffice_admins_path,
        success: t('alerts.deleted_alert', item: admin_email)
        #notice: t('alerts.deleted_alert', item: admin_email)
    else
      render :index
    end
  end

  private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      if password_blank?
        params[:admin].except!(:password, :password_confirmation)
      end

      if @admin.blank?
        # For create action
        params.require(:admin)
          .permit(:name, :email, :role, :password, :password_confirmation)
      else
        # For edit, update and destroy actions
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params.dig(:password).blank? &&
      params.dig(:password_confirmation).blank?
    end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    if @category.errors.any?
      render :new,
      #notice: I18n.t('alerts.created_error_alert', item: @category.description)
      danger: I18n.t('alerts.created_error_alert', item: @category.description)
    else
      redirect_to backoffice_categories_path, 
      #notice: I18n.t('alerts.created_alert', item: @category.description)
      success: I18n.t('alerts.created_alert', item: @category.description)
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, 
        #notice: I18n.t('alerts.updated_alert', item: @category.description)
        success: I18n.t('alerts.updated_alert', item: @category.description)
    else
      render :edit
    end
  end

  def destroy
    category_description = @category.description
    if @category.destroy
      redirect_to backoffice_categories_path, 
        # notice: I18n.t('alerts.deleted_alert', item: category_description)
        success: I18n.t('alerts.deleted_alert', item: category_description)
    else
      render :index
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin, 
                               params[:'recipient-text'],
                               params[:'subject-text'],
                               params[:'message-text']).deliver_now
      @notify_message = t('alerts.email_sent_sucessfully_alert')
      @notify_flag = "success"
    rescue
      @notify_message = t('alerts.email_error_alert')
      @notify_flag = "error"
    end
                             
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout "backoffice"

  # customized user type in pundit
  def pundit_user
    current_admin # current_user to Pundit
  end

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)
  
  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", 
  locals: {action: t('messages.editing_label', model: Admin.model_name.human)} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header"><%= @admins.model.model_name.human(count: 2) %></h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= t('messages.listing_label', model: @admins.model.model_name.human(count: 2)) %>

    <% if policy(@admins).new? %>
      <%= link_to new_backoffice_admin_path, 
        title: t('buttons.add_model_button', model: @admins.model.model_name),
        class:"btn btn-success btn-circle pull-right", 
        style:"margin-top: -5px" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    <% else %>
      <%= link_to '#', disabled: 'disabled', 
        class:"btn btn-success btn-circle pull-right", 
        style:"margin-top: -5px" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    <% end %>

  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th><%= @admins.model.human_attribute_name("name") %></th>
              <th><%= @admins.model.human_attribute_name("email") %></th>
              <th><%= @admins.model.human_attribute_name("role") %></th>
              <th>Ações</th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %> 
              <tr>
                <td style="width: 30px"><%= admin.id %></td>
                <td><%= admin.name %></td>
                <td><%= admin.email %></td>
                <td><%= admin.role_i18n %></td>
                <td style="width: 115px">
                 
                  <%= link_to edit_backoffice_send_mail_path(admin.id), 
                    class:"btn btn-info btn-circle", 
                    title: t('buttons.send_email_button'), remote: true do %>
                    <i class="fa fa-envelope"></i>
                  <% end %>
                
                  <%= link_to edit_backoffice_admin_path(admin.id), 
                    title: t('buttons.edit_button'), class:"btn btn-warning btn-circle" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  
                  <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>
                    <%= link_to backoffice_admin_path(admin.id), 
                      title: t('buttons.delete_button'),
                      method: :delete, class: "btn btn-danger btn-circle",
                      data: { confirm: t('alerts.confirm_with_alert', 
                      item: admin.name)} do %>
                      <i class="fa fa-trash-o"></i>
                    <% end %>
                  <% else %>
                    <%= link_to '#', class: "btn btn-danger btn-circle",
                      title: t('buttons.delete_button'), disabled: "disabled" do %>
                        <i class="fa fa-trash-o"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>
<!-- /.panel -->

<%= render partial: 'backoffice/admins/shared/send_mail_modal' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", 
    locals: {action: t('messages.creating_label', model: Admin.model_name.human) }%>